apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
    name: my-job-name33
spec:
    image: my-image-name:eee1.0.0
    flinkVersion: v1_14
    flinkConfiguration:
        taskmanager.numberOfTaskSlots: "2"
        state.savepoints.dir:
            savepoints:
                dir: ""
        state.checkpoints.dir:
            checkpoits:
                dir: ""
    serviceAccount: flink
    podTemplate:
        apiVersion: v1
        kind: Pod
        metadata:
            name: pod-template
        spec:
            serviceAccount: flink
            tolerations:
                - effect: NoExecute
                  key: spot
                  operator: Equal
                  value: "true"
                - effect: NoSchedule
                  key: spot
                  operator: Equal
                  value: "true"
    jobManager:
        resource:
            memory: 2048m
            cpu: 1
        podTemplate:
            apiVersion: v1
            kind: Pod
            spec:
                affinity:
                    nodeAffinity:
                        requiredDuringSchedulingIgnoredDuringExecution:
                            nodeSelectorTerms:
                                - matchExpressions:
                                    - key: family
                                      operator: In
                                      values:
                                        - value
                                    - key: team-ops/workload
                                      operator: In
                                      values:
                                        - value
                                    - key: app
                                      operator: In
                                      values:
                                        - value
    taskManager:
        resource:
            memory: 2048m
            cpu: 1
    job:
        jarURI: local:///opt/flink/usrlib/my-flink-job.jar
        parallelism: 2
        upgradeMode: savepoint
        state: running
        args:
            - --source-servers
            - b-5.k
            - --source-topic
            - complex
            - --source-group-id
            - my-job-name-op
            - --sink-topic
            - my-job-name
            - --sink-servers
            - joba,jobc,joba
