# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

helmapi:
  image:
    repository: rhiadciccoli/testapi
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

